export const data = {
    products: [
        {
            name:'Nike Slim shirt',
            slug: 'nike-slim-shirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price:120,
            countInStock:10,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'High quality shirt',
        },
        {
            name:'Adidas Slim shirt',
            slug: 'adidas-slim-shirt',
            category: 'Shirts',
            image: '/images/p2.jpg',
            price:100,
            countInStock:7,
            brand:'Adidas',
            rating:4.0,
            numReviews:40,
            description:'High quality shirt',
        },
        {
            name:'Adidas Slim Pant',
            slug: 'adidas-slim-pant',
            category: 'Pants',
            image: '/images/p3.jpg',
            price:140,
            countInStock:0,
            brand:'Adidas',
            rating:4.0,
            numReviews:13,
            description:'High quality product',
        },
        {
            name:'Nike Slim Pant',
            slug: 'nike-slim-pant',
            category: 'Pants',
            image: '/images/p4.jpg',
            price:150,
            countInStock:15,
            brand:'Nike',
            rating:4.3,
            numReviews:9,
            description:'High quality pants',
        },
    ]
}